/**
 * TZ §20 — stable error-code registry.
 *
 * ⚠️ APPEND-ONLY. Codes are part of the public API contract (mobile app + web panel
 * branch on them). Never rename, never renumber, never delete. Add new codes at the
 * bottom of the relevant block.
 */
export const ERROR_CODES = {
  // --- generic / transport -------------------------------------------------
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // --- auth / rbac (TZ §6) -------------------------------------------------
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  USER_NOT_INVITED: 'USER_NOT_INVITED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ROLE_IMMUTABLE: 'ROLE_IMMUTABLE',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  DRIVER_CONTEXT_REQUIRED: 'DRIVER_CONTEXT_REQUIRED',

  // --- fleet (TZ §5.3, §5.4) ----------------------------------------------
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_ALREADY_PAIRED: 'DEVICE_ALREADY_PAIRED',
  VEHICLE_OUT_OF_SERVICE: 'VEHICLE_OUT_OF_SERVICE',
  /** §5.10 hard rule — cannot set `Vehicle.status` to a non-OOS value while an OPEN CRITICAL
   * defect exists on the unit. Payload lists the blocking defect ids. */
  VEHICLE_HAS_OPEN_CRITICAL_DEFECTS: 'VEHICLE_HAS_OPEN_CRITICAL_DEFECTS',
  ODOMETER_ANOMALY: 'ODOMETER_ANOMALY',
  ODOMETER_NOT_CALIBRATED: 'ODOMETER_NOT_CALIBRATED',
  IMPORT_FAILED: 'IMPORT_FAILED',

  // --- ingest (TZ §7) ------------------------------------------------------
  CHECKSUM_MISMATCH: 'CHECKSUM_MISMATCH',
  DUPLICATE_EVENT: 'DUPLICATE_EVENT',
  EVENT_SEQUENCE_IMMUTABLE: 'EVENT_SEQUENCE_IMMUTABLE',
  EVENT_OUT_OF_RANGE: 'EVENT_OUT_OF_RANGE',
  BATCH_TOO_LARGE: 'BATCH_TOO_LARGE',
  UNKNOWN_DEVICE: 'UNKNOWN_DEVICE',

  // --- HOS / RODS (TZ §8, §9) ---------------------------------------------
  DRIVING_TIME_IMMUTABLE: 'DRIVING_TIME_IMMUTABLE',
  LOG_ALREADY_CERTIFIED: 'LOG_ALREADY_CERTIFIED',
  RECERTIFICATION_REQUIRED: 'RECERTIFICATION_REQUIRED',
  EDIT_REQUIRES_DRIVER_APPROVAL: 'EDIT_REQUIRES_DRIVER_APPROVAL',
  EDIT_ALREADY_RESOLVED: 'EDIT_ALREADY_RESOLVED',
  UNCERTIFIED_LOGS: 'UNCERTIFIED_LOGS',
  UNRESOLVED_UNIDENTIFIED: 'UNRESOLVED_UNIDENTIFIED',
  UNIDENTIFIED_ALREADY_ASSIGNED: 'UNIDENTIFIED_ALREADY_ASSIGNED',
  HOS_ENGINE_VERSION_MISMATCH: 'HOS_ENGINE_VERSION_MISMATCH',

  // --- transfers / eRODS (TZ §10) -----------------------------------------
  INVALID_TRANSFER_RECIPIENT: 'INVALID_TRANSFER_RECIPIENT',
  TRANSFER_VALIDATION_FAILED: 'TRANSFER_VALIDATION_FAILED',
  ERODS_TEST_MODE_ONLY: 'ERODS_TEST_MODE_ONLY',
  RANGE_TOO_LARGE: 'RANGE_TOO_LARGE',
  /** §10.4 — `FMCSA_PUBLIC_KEY` missing/unparsable: an email transfer cannot be encrypted. */
  TRANSFER_ENCRYPTION_UNAVAILABLE: 'TRANSFER_ENCRYPTION_UNAVAILABLE',
  /** §10.4 — an email transfer job reached the send step with `encrypted = false`. */
  TRANSFER_NOT_ENCRYPTED: 'TRANSFER_NOT_ENCRYPTED',
  /** The generated output file failed Appendix A validation — never handed to an inspector. */
  OUTPUT_FILE_INVALID: 'OUTPUT_FILE_INVALID',

  // --- DVIR / maintenance (TZ §5.10) --------------------------------------
  DVIR_ALREADY_SIGNED: 'DVIR_ALREADY_SIGNED',
  DEFECT_NOT_RESOLVED: 'DEFECT_NOT_RESOLVED',
  WORK_ORDER_CLOSED: 'WORK_ORDER_CLOSED',
  DVIR_NOT_FOUND: 'DVIR_NOT_FOUND',
  DEFECT_NOT_FOUND: 'DEFECT_NOT_FOUND',
  WORK_ORDER_NOT_FOUND: 'WORK_ORDER_NOT_FOUND',
  MAINTENANCE_SCHEDULE_NOT_FOUND: 'MAINTENANCE_SCHEDULE_NOT_FOUND',

  // --- notifications / messaging (TZ §14) ---------------------------------
  CHANNEL_NOT_AVAILABLE: 'CHANNEL_NOT_AVAILABLE',
  ALERT_RULE_INVALID: 'ALERT_RULE_INVALID',

  // --- sync / realtime (TZ §12, §13) --------------------------------------
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  SYNC_CURSOR_INVALID: 'SYNC_CURSOR_INVALID',
  RESUME_WINDOW_EXPIRED: 'RESUME_WINDOW_EXPIRED',
  /** §13.4 — batch over 500 changes or 1 MB. */
  SYNC_BATCH_TOO_LARGE: 'SYNC_BATCH_TOO_LARGE',
  /** §13.4 — a change `type` the server does not recognise (client is ahead of the server). */
  SYNC_UNKNOWN_CHANGE_TYPE: 'SYNC_UNKNOWN_CHANGE_TYPE',

  // --- reports (TZ §15) -----------------------------------------------------
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_NOT_READY: 'REPORT_NOT_READY',
  REPORT_SCHEDULE_NOT_FOUND: 'REPORT_SCHEDULE_NOT_FOUND',
  INVALID_CRON_EXPRESSION: 'INVALID_CRON_EXPRESSION',

  // --- storage / integrations (TZ §16, §17) -------------------------------
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
  INTEGRATION_NOT_CONFIGURED: 'INTEGRATION_NOT_CONFIGURED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
