-- Reverts 20261008131000_defect_catalog_design_rows (M-29).
-- Rows this migration INSERTED (not part of the original 47) are removed, the original rows get their
-- previous name / order back and are re-activated, then the column is dropped.
DELETE FROM "DefectCatalogItem"
WHERE ("part", "code") NOT IN (
  SELECT o.part::"DefectPart", o.code FROM (VALUES
    ('TRUCK', 'AIR_LINES'),
    ('TRUCK', 'BATTERY'),
    ('TRUCK', 'BRAKES_PARKING'),
    ('TRUCK', 'BRAKES_SERVICE'),
    ('TRUCK', 'CLUTCH'),
    ('TRUCK', 'COUPLING_DEVICE'),
    ('TRUCK', 'DEFROSTER_HEATER'),
    ('TRUCK', 'ENGINE'),
    ('TRUCK', 'EXHAUST'),
    ('TRUCK', 'FIFTH_WHEEL'),
    ('TRUCK', 'FLUID_LEVELS'),
    ('TRUCK', 'FRAME_ASSEMBLY'),
    ('TRUCK', 'FUEL_TANKS'),
    ('TRUCK', 'HORN'),
    ('TRUCK', 'LIGHTS_HEAD_STOP'),
    ('TRUCK', 'LIGHTS_TURN_MARKER'),
    ('TRUCK', 'MIRRORS'),
    ('TRUCK', 'OIL_PRESSURE'),
    ('TRUCK', 'RADIATOR'),
    ('TRUCK', 'REAR_END'),
    ('TRUCK', 'REFLECTORS'),
    ('TRUCK', 'SAFETY_EQUIPMENT'),
    ('TRUCK', 'STARTER'),
    ('TRUCK', 'STEERING'),
    ('TRUCK', 'SUSPENSION'),
    ('TRUCK', 'TIRES'),
    ('TRUCK', 'TRANSMISSION'),
    ('TRUCK', 'TRIP_RECORDER'),
    ('TRUCK', 'WHEELS_RIMS'),
    ('TRUCK', 'WINDOWS'),
    ('TRUCK', 'WINDSHIELD_WIPERS'),
    ('TRUCK', 'OTHER'),
    ('TRAILER', 'BRAKE_CONNECTIONS'),
    ('TRAILER', 'BRAKES'),
    ('TRAILER', 'COUPLING_DEVICES'),
    ('TRAILER', 'COUPLING_KING_PIN'),
    ('TRAILER', 'DOORS'),
    ('TRAILER', 'HITCH'),
    ('TRAILER', 'LANDING_GEAR'),
    ('TRAILER', 'LIGHTS'),
    ('TRAILER', 'REFLECTORS'),
    ('TRAILER', 'ROOF'),
    ('TRAILER', 'SUSPENSION'),
    ('TRAILER', 'TARPAULIN'),
    ('TRAILER', 'TIRES'),
    ('TRAILER', 'WHEELS_RIMS'),
    ('TRAILER', 'OTHER')
  ) AS o(part, code)
);

UPDATE "DefectCatalogItem" AS t
SET "name" = o.name, "sortOrder" = o."sortOrder", "active" = true
FROM (VALUES
    ('TRUCK', 'AIR_LINES', 'Air lines', 10),
    ('TRUCK', 'BATTERY', 'Battery', 20),
    ('TRUCK', 'BRAKES_PARKING', 'Brakes, Parking', 30),
    ('TRUCK', 'BRAKES_SERVICE', 'Brakes, Service', 40),
    ('TRUCK', 'CLUTCH', 'Clutch', 50),
    ('TRUCK', 'COUPLING_DEVICE', 'Coupling device', 60),
    ('TRUCK', 'DEFROSTER_HEATER', 'Defroster/Heater', 70),
    ('TRUCK', 'ENGINE', 'Engine', 80),
    ('TRUCK', 'EXHAUST', 'Exhaust', 90),
    ('TRUCK', 'FIFTH_WHEEL', 'Fifth wheel', 100),
    ('TRUCK', 'FLUID_LEVELS', 'Fluid levels', 110),
    ('TRUCK', 'FRAME_ASSEMBLY', 'Frame & assembly', 120),
    ('TRUCK', 'FUEL_TANKS', 'Fuel tanks', 130),
    ('TRUCK', 'HORN', 'Horn', 140),
    ('TRUCK', 'LIGHTS_HEAD_STOP', 'Lights (Head - Stop)', 150),
    ('TRUCK', 'LIGHTS_TURN_MARKER', 'Lights (Turn - Marker)', 160),
    ('TRUCK', 'MIRRORS', 'Mirrors', 170),
    ('TRUCK', 'OIL_PRESSURE', 'Oil pressure', 180),
    ('TRUCK', 'RADIATOR', 'Radiator', 190),
    ('TRUCK', 'REAR_END', 'Rear end', 200),
    ('TRUCK', 'REFLECTORS', 'Reflectors', 210),
    ('TRUCK', 'SAFETY_EQUIPMENT', 'Safety equipment', 220),
    ('TRUCK', 'STARTER', 'Starter', 230),
    ('TRUCK', 'STEERING', 'Steering', 240),
    ('TRUCK', 'SUSPENSION', 'Suspension', 250),
    ('TRUCK', 'TIRES', 'Tires', 260),
    ('TRUCK', 'TRANSMISSION', 'Transmission', 270),
    ('TRUCK', 'TRIP_RECORDER', 'Trip recorder', 280),
    ('TRUCK', 'WHEELS_RIMS', 'Wheels & rims', 290),
    ('TRUCK', 'WINDOWS', 'Windows', 300),
    ('TRUCK', 'WINDSHIELD_WIPERS', 'Windshield wipers', 310),
    ('TRUCK', 'OTHER', 'Other', 320),
    ('TRAILER', 'BRAKE_CONNECTIONS', 'Brake connections', 10),
    ('TRAILER', 'BRAKES', 'Brakes', 20),
    ('TRAILER', 'COUPLING_DEVICES', 'Coupling devices', 30),
    ('TRAILER', 'COUPLING_KING_PIN', 'Coupling (king) pin', 40),
    ('TRAILER', 'DOORS', 'Doors', 50),
    ('TRAILER', 'HITCH', 'Hitch', 60),
    ('TRAILER', 'LANDING_GEAR', 'Landing gear', 70),
    ('TRAILER', 'LIGHTS', 'Lights', 80),
    ('TRAILER', 'REFLECTORS', 'Reflectors', 90),
    ('TRAILER', 'ROOF', 'Roof', 100),
    ('TRAILER', 'SUSPENSION', 'Suspension', 110),
    ('TRAILER', 'TARPAULIN', 'Tarpaulin', 120),
    ('TRAILER', 'TIRES', 'Tires', 130),
    ('TRAILER', 'WHEELS_RIMS', 'Wheels & rims', 140),
    ('TRAILER', 'OTHER', 'Other', 150)
) AS o(part, code, name, "sortOrder")
WHERE t."part" = o.part::"DefectPart" AND t."code" = o.code;

ALTER TABLE "DefectCatalogItem" DROP COLUMN "isPhoto";
