-- M-29 (mobile wave 4, 2026-10-08): the app ships the DESIGN's defect list; `GET /mobile/defect-catalog`
-- must return exactly these names in this order (42 truck + 16 trailer). Rows not in the design list are
-- HIDDEN (active = false), never deleted: earlier DVIRs reference their codes.
-- `isPhoto` marks the "Accident Photo" row (a photo capture, not an inspection item).
ALTER TABLE "DefectCatalogItem" ADD COLUMN "isPhoto" BOOLEAN NOT NULL DEFAULT false;

-- Design rows: upsert on (part, code). An existing row keeps its category/critical; name, order and
-- visibility come from the design.
INSERT INTO "DefectCatalogItem" ("id", "part", "code", "name", "category", "critical", "sortOrder", "isPhoto", "active") 
SELECT gen_random_uuid(), d.part::"DefectPart", d.code, d.name, d.category, d.critical, d."sortOrder", d."isPhoto", true
FROM (VALUES
  ('TRUCK', 'ACCIDENT_PHOTO', 'Accident Photo', 'Accident', false, 10, true),
  ('TRUCK', 'ENGINE', 'Engine', 'Engine', false, 20, false),
  ('TRUCK', 'BATTERY', 'Battery', 'Electrical', false, 30, false),
  ('TRUCK', 'EXHAUST', 'Exhaust', 'Engine', false, 40, false),
  ('TRUCK', 'AIR_LINES', 'Air Lines', 'Brakes', true, 50, false),
  ('TRUCK', 'BODY', 'Body', 'Body', false, 60, false),
  ('TRUCK', 'BRAKE_ACCESSORIES', 'Brake Accessories', 'Brakes', true, 70, false),
  ('TRUCK', 'BRAKES_PARKING', 'Brakes, Parking', 'Brakes', true, 80, false),
  ('TRUCK', 'BRAKES_SERVICE', 'Brakes, Service', 'Brakes', true, 90, false),
  ('TRUCK', 'CLUTCH', 'Clutch', 'Drivetrain', false, 100, false),
  ('TRUCK', 'COUPLING_DEVICE', 'Coupling Device', 'Coupling', true, 110, false),
  ('TRUCK', 'DEFROSTER_HEATER', 'Defroster/Heater', 'Cab', false, 120, false),
  ('TRUCK', 'DRIVE_LINE', 'Drive Line', 'Drivetrain', false, 130, false),
  ('TRUCK', 'FIFTH_WHEEL', 'Fifth Wheel', 'Coupling', true, 140, false),
  ('TRUCK', 'FRAME_AND_ASSEMBLY', 'Frame and Assembly', 'Chassis', true, 150, false),
  ('TRUCK', 'FRONT_AXLE', 'Front Axle', 'Chassis', true, 160, false),
  ('TRUCK', 'FUEL_TANKS', 'Fuel Tanks', 'Engine', false, 170, false),
  ('TRUCK', 'GENERATOR', 'Generator', 'Electrical', false, 180, false),
  ('TRUCK', 'HORN', 'Horn', 'Cab', false, 190, false),
  ('TRUCK', 'LIGHTS_HEAD_STOP', 'Lights - Head/Stop', 'Lights', true, 200, false),
  ('TRUCK', 'LIGHTS_TAIL_DASH', 'Lights - Tail/Dash', 'Lights', false, 210, false),
  ('TRUCK', 'LIGHTS_TURN_INDICATORS', 'Lights - Turn Indicators', 'Lights', false, 220, false),
  ('TRUCK', 'MIRRORS', 'Mirrors', 'Cab', false, 230, false),
  ('TRUCK', 'MUFFLER', 'Muffler', 'Engine', false, 240, false),
  ('TRUCK', 'OIL_PRESSURE', 'Oil Pressure', 'Engine', false, 250, false),
  ('TRUCK', 'RADIATOR', 'Radiator', 'Engine', false, 260, false),
  ('TRUCK', 'REAR_END', 'Rear End', 'Drivetrain', false, 270, false),
  ('TRUCK', 'REFLECTORS', 'Reflectors', 'Lights', false, 280, false),
  ('TRUCK', 'SAFETY_EQUIPMENT_FIRE_EXTINGUISHER', 'Safety Equipment - Fire Extinguisher', 'Safety', false, 290, false),
  ('TRUCK', 'SAFETY_EQUIPMENT_FLAGS_FLARES_FUSEES', 'Safety Equipment - Flags/Flares/Fusees', 'Safety', false, 300, false),
  ('TRUCK', 'SAFETY_EQUIPMENT_SPARE_BULBS_FUSES', 'Safety Equipment - Spare Bulbs & Fuses', 'Safety', false, 310, false),
  ('TRUCK', 'SPRINGS', 'Springs', 'Chassis', true, 320, false),
  ('TRUCK', 'STARTER', 'Starter', 'Electrical', false, 330, false),
  ('TRUCK', 'STEERING', 'Steering', 'Steering', true, 340, false),
  ('TRUCK', 'TACHOGRAPH', 'Tachograph', 'Cab', false, 350, false),
  ('TRUCK', 'TIRES', 'Tires', 'Tires & wheels', true, 360, false),
  ('TRUCK', 'TRANSMISSION', 'Transmission', 'Drivetrain', false, 370, false),
  ('TRUCK', 'WHEELS_AND_RIMS', 'Wheels and Rims', 'Tires & wheels', true, 380, false),
  ('TRUCK', 'WINDOWS', 'Windows', 'Cab', false, 390, false),
  ('TRUCK', 'WINDSHIELD_WIPERS', 'Windshield Wipers', 'Cab', false, 400, false),
  ('TRUCK', 'OTHER', 'Other', NULL, false, 410, false),
  ('TRAILER', 'BRAKE_CONNECTIONS', 'Brake Connections', 'Brakes', true, 10, false),
  ('TRAILER', 'BRAKES', 'Brakes', 'Brakes', true, 20, false),
  ('TRAILER', 'COUPLING_CHAINS', 'Coupling Chains', 'Coupling', true, 30, false),
  ('TRAILER', 'COUPLING_KING_PIN', 'Coupling (King) Pin', 'Coupling', true, 40, false),
  ('TRAILER', 'DOORS', 'Doors', 'Body', false, 50, false),
  ('TRAILER', 'HITCH', 'Hitch', 'Coupling', true, 60, false),
  ('TRAILER', 'LANDING_GEAR', 'Landing Gear', 'Chassis', false, 70, false),
  ('TRAILER', 'LIGHTS_ALL', 'Lights - All', 'Lights', false, 80, false),
  ('TRAILER', 'REFLECTORS_REFLECTIVE_TAPE', 'Reflectors/Reflective Tape', 'Lights', false, 90, false),
  ('TRAILER', 'ROOF', 'Roof', 'Body', false, 100, false),
  ('TRAILER', 'SPRINGS', 'Springs', 'Chassis', true, 110, false),
  ('TRAILER', 'SUSPENSION_SYSTEM', 'Suspension System', 'Chassis', true, 120, false),
  ('TRAILER', 'TARPAULIN', 'Tarpaulin', 'Body', false, 130, false),
  ('TRAILER', 'TIRES', 'Tires', 'Tires & wheels', true, 140, false),
  ('TRAILER', 'WHEELS_AND_RIMS', 'Wheels and Rims', 'Tires & wheels', true, 150, false),
  ('TRAILER', 'OTHER', 'Other', NULL, false, 160, false)
) AS d(part, code, name, category, critical, "sortOrder", "isPhoto")
ON CONFLICT ("part", "code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "sortOrder" = EXCLUDED."sortOrder",
  "isPhoto" = EXCLUDED."isPhoto",
  "active" = true;

-- Everything else is hidden (not deleted).
UPDATE "DefectCatalogItem" SET "active" = false
WHERE ("part", "code") NOT IN (
  SELECT d.part::"DefectPart", d.code FROM (VALUES
    ('TRUCK', 'ACCIDENT_PHOTO'),
    ('TRUCK', 'ENGINE'),
    ('TRUCK', 'BATTERY'),
    ('TRUCK', 'EXHAUST'),
    ('TRUCK', 'AIR_LINES'),
    ('TRUCK', 'BODY'),
    ('TRUCK', 'BRAKE_ACCESSORIES'),
    ('TRUCK', 'BRAKES_PARKING'),
    ('TRUCK', 'BRAKES_SERVICE'),
    ('TRUCK', 'CLUTCH'),
    ('TRUCK', 'COUPLING_DEVICE'),
    ('TRUCK', 'DEFROSTER_HEATER'),
    ('TRUCK', 'DRIVE_LINE'),
    ('TRUCK', 'FIFTH_WHEEL'),
    ('TRUCK', 'FRAME_AND_ASSEMBLY'),
    ('TRUCK', 'FRONT_AXLE'),
    ('TRUCK', 'FUEL_TANKS'),
    ('TRUCK', 'GENERATOR'),
    ('TRUCK', 'HORN'),
    ('TRUCK', 'LIGHTS_HEAD_STOP'),
    ('TRUCK', 'LIGHTS_TAIL_DASH'),
    ('TRUCK', 'LIGHTS_TURN_INDICATORS'),
    ('TRUCK', 'MIRRORS'),
    ('TRUCK', 'MUFFLER'),
    ('TRUCK', 'OIL_PRESSURE'),
    ('TRUCK', 'RADIATOR'),
    ('TRUCK', 'REAR_END'),
    ('TRUCK', 'REFLECTORS'),
    ('TRUCK', 'SAFETY_EQUIPMENT_FIRE_EXTINGUISHER'),
    ('TRUCK', 'SAFETY_EQUIPMENT_FLAGS_FLARES_FUSEES'),
    ('TRUCK', 'SAFETY_EQUIPMENT_SPARE_BULBS_FUSES'),
    ('TRUCK', 'SPRINGS'),
    ('TRUCK', 'STARTER'),
    ('TRUCK', 'STEERING'),
    ('TRUCK', 'TACHOGRAPH'),
    ('TRUCK', 'TIRES'),
    ('TRUCK', 'TRANSMISSION'),
    ('TRUCK', 'WHEELS_AND_RIMS'),
    ('TRUCK', 'WINDOWS'),
    ('TRUCK', 'WINDSHIELD_WIPERS'),
    ('TRUCK', 'OTHER'),
    ('TRAILER', 'BRAKE_CONNECTIONS'),
    ('TRAILER', 'BRAKES'),
    ('TRAILER', 'COUPLING_CHAINS'),
    ('TRAILER', 'COUPLING_KING_PIN'),
    ('TRAILER', 'DOORS'),
    ('TRAILER', 'HITCH'),
    ('TRAILER', 'LANDING_GEAR'),
    ('TRAILER', 'LIGHTS_ALL'),
    ('TRAILER', 'REFLECTORS_REFLECTIVE_TAPE'),
    ('TRAILER', 'ROOF'),
    ('TRAILER', 'SPRINGS'),
    ('TRAILER', 'SUSPENSION_SYSTEM'),
    ('TRAILER', 'TARPAULIN'),
    ('TRAILER', 'TIRES'),
    ('TRAILER', 'WHEELS_AND_RIMS'),
    ('TRAILER', 'OTHER')
  ) AS d(part, code)
);
